# this class is autogenerated.  use make_zones to regenerate
package Data::ICal::TimeZone::Object::Indian::Cocos;
use strict;
use base qw( Data::ICal::TimeZone::Object );

__PACKAGE__->new->_load( join '', <DATA> );

1;
__DATA__
BEGIN:VCALENDAR
PRODID:-//My Organization//NONSGML My Product//EN
VERSION:2.0
BEGIN:VTIMEZONE
TZID:Indian/Cocos
X-LIC-LOCATION:Indian/Cocos
BEGIN:STANDARD
TZOFFSETFROM:+0630
TZOFFSETTO:+0630
TZNAME:CCT
DTSTART:19700101T000000
END:STANDARD
END:VTIMEZONE
END:VCALENDAR
